language: python

python:
  - 2.7
  - 3.4

install:
  - pip install tox flake8 six
  - make install

script:
  - make flake8
  - tox

notifications:
          email:
            - hannes@5monkeys.se

