[build-system]
requires = ["setuptools>=57.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
python_files = "tests.py test_*.py *_tests.py"
testpaths = ["django_enumfield"]
pythonpath = "django_enumfield"
addopts = "--cov --no-cov-on-fail"
